In [1]:
import pandas as pd
import re

# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

# Update the path to match your Drive structure
file_path = '/content/drive/My Drive/Pranamya Financial Services/DAILY DATA/Input folder/Holdings Daily/HOLDING 22 APRIL 2026.XLSX'


df_raw = pd.read_excel(file_path, header=1)

# 2. Extract data starting after header row
df = df_raw.copy()

# Columns are in row 0
#df.columns = df.iloc[0]
#df = df[1:].reset_index(drop=True)

# Add columns for client info
df['Client Code'] = None
df['Client Name'] = None

current_code = None
current_name = None

df.head()

Mounted at /content/drive

,ISIN Code,ISIN_x000D_\nDescription,Total_x000D_\nBalance,Closing_x000D_\nRate,Holding_x000D_\nValuation,Pledged/_x000D_\nFreeze,Unnamed: 6,Free_x000D_\nBalance,Client Code,Client Name
0,1205910001004282 ABHAY PREMDAS TEMBHURNE [NGPM...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None
1,INE00FF01025,ACUTAAS CHEM-EQ5/-,5.0,2372.80,11864.00,0.0,,5.0,None,None
2,INE931S01010,ADANI ENERGY-EQ,2.0,1265.30,2530.60,0.0,,2.0,None,None
3,INE006I01046,ASTRAL LIMITED-EQ,1.0,1583.75,1583.75,0.0,,1.0,None,None
4,INE871C01038,AVANTI FEEDS-EQ1/-,3.0,1464.85,4394.55,0.0,,3.0,None,None

In [2]:
df.head()

,ISIN Code,ISIN_x000D_\nDescription,Total_x000D_\nBalance,Closing_x000D_\nRate,Holding_x000D_\nValuation,Pledged/_x000D_\nFreeze,Unnamed: 6,Free_x000D_\nBalance,Client Code,Client Name
0,1205910001004282 ABHAY PREMDAS TEMBHURNE [NGPM...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None
1,INE00FF01025,ACUTAAS CHEM-EQ5/-,5.0,2372.80,11864.00,0.0,,5.0,None,None
2,INE931S01010,ADANI ENERGY-EQ,2.0,1265.30,2530.60,0.0,,2.0,None,None
3,INE006I01046,ASTRAL LIMITED-EQ,1.0,1583.75,1583.75,0.0,,1.0,None,None
4,INE871C01038,AVANTI FEEDS-EQ1/-,3.0,1464.85,4394.55,0.0,,3.0,None,None

In [3]:
# Add columns for client info
df['Client Code'] = None
df['Client Name'] = None

current_code = None
current_name = None

In [4]:
df.head(10)

,ISIN Code,ISIN_x000D_\nDescription,Total_x000D_\nBalance,Closing_x000D_\nRate,Holding_x000D_\nValuation,Pledged/_x000D_\nFreeze,Unnamed: 6,Free_x000D_\nBalance,Client Code,Client Name
0,1205910001004282 ABHAY PREMDAS TEMBHURNE [NGPM...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None
1,INE00FF01025,ACUTAAS CHEM-EQ5/-,5.0,2372.80,11864.00,0.0,,5.0,None,None
2,INE931S01010,ADANI ENERGY-EQ,2.0,1265.30,2530.60,0.0,,2.0,None,None
3,INE006I01046,ASTRAL LIMITED-EQ,1.0,1583.75,1583.75,0.0,,1.0,None,None
4,INE871C01038,AVANTI FEEDS-EQ1/-,3.0,1464.85,4394.55,0.0,,3.0,None,None
5,INE894V01022,BELRISE INDUSTRIE-EQ,3.0,219.15,657.45,0.0,,3.0,None,None
6,INE263A01024,BHARAT ELECTRONIC-EQ,4.0,451.55,1806.20,0.0,,4.0,None,None
7,INE465A01025,BHARAT FORGE-NEW RS2,1.0,1895.35,1895.35,0.0,,1.0,None,None
8,INE118H01025,BSE LIMITED-EQ 2/-,1.0,3515.80,3515.80,0.0,,1.0,None,None
9,INE495A01022,DALMIA BHARA EQ RS 2,1.0,383.55,383.55,0.0,,1.0,None,None

In [5]:
# 3. Iterate through all rows
for i, row in df_raw.iterrows():
    first_col = str(row[0]).strip() if not pd.isna(row[0]) else ""
    # Detect client header row
    if re.match(r'^\d{16}\s', first_col):
        m = re.match(r'^(\d{16})\s+(.+?)\s+\[(.+?)\]$', first_col)
        if m:
            current_code = m.group(1)
            current_name = f"{m.group(2).strip()} [{m.group(3).strip()}]"
        continue
    # Detect ISIN row and assign
    #if i > 0 and first_col.startswith("IN") and current_code and current_name:
    if i > 0 and first_col.startswith("IN") or first_col.startswith("*IN")and current_code and current_name:
        df.at[i, 'Client Code'] = current_code
        df.at[i, 'Client Name'] = current_name

/tmp/ipykernel_1024/2221514117.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  first_col = str(row[0]).strip() if not pd.isna(row[0]) else ""

In [6]:
df.head()

,ISIN Code,ISIN_x000D_\nDescription,Total_x000D_\nBalance,Closing_x000D_\nRate,Holding_x000D_\nValuation,Pledged/_x000D_\nFreeze,Unnamed: 6,Free_x000D_\nBalance,Client Code,Client Name
0,1205910001004282 ABHAY PREMDAS TEMBHURNE [NGPM...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None
1,INE00FF01025,ACUTAAS CHEM-EQ5/-,5.0,2372.80,11864.00,0.0,,5.0,1205910001004282,ABHAY PREMDAS TEMBHURNE [NGPM071]
2,INE931S01010,ADANI ENERGY-EQ,2.0,1265.30,2530.60,0.0,,2.0,1205910001004282,ABHAY PREMDAS TEMBHURNE [NGPM071]
3,INE006I01046,ASTRAL LIMITED-EQ,1.0,1583.75,1583.75,0.0,,1.0,1205910001004282,ABHAY PREMDAS TEMBHURNE [NGPM071]
4,INE871C01038,AVANTI FEEDS-EQ1/-,3.0,1464.85,4394.55,0.0,,3.0,1205910001004282,ABHAY PREMDAS TEMBHURNE [NGPM071]

In [7]:
df.columns = df.columns.str.replace('_x000D_\\n', ' ', regex=True)

In [8]:
# 4. Keep only ISIN rows
#df_final = df[df.iloc[:, 0].astype(str).str.startswith('IN', na=False)]

df_final = df[df.iloc[:, 0].astype(str).str.match(r'^\*?IN')]

In [9]:
# 5. Reorder columns
cols = ['Client Code', 'Client Name'] + [c for c in df_final.columns if c not in ['Client Code', 'Client Name']]
df_final = df_final[cols]

In [10]:
df_final.head()

,Client Code,Client Name,ISIN Code,ISIN Description,Total Balance,Closing Rate,Holding Valuation,Pledged/ Freeze,Unnamed: 6,Free Balance
1,1205910001004282,ABHAY PREMDAS TEMBHURNE [NGPM071],INE00FF01025,ACUTAAS CHEM-EQ5/-,5.0,2372.80,11864.00,0.0,,5.0
2,1205910001004282,ABHAY PREMDAS TEMBHURNE [NGPM071],INE931S01010,ADANI ENERGY-EQ,2.0,1265.30,2530.60,0.0,,2.0
3,1205910001004282,ABHAY PREMDAS TEMBHURNE [NGPM071],INE006I01046,ASTRAL LIMITED-EQ,1.0,1583.75,1583.75,0.0,,1.0
4,1205910001004282,ABHAY PREMDAS TEMBHURNE [NGPM071],INE871C01038,AVANTI FEEDS-EQ1/-,3.0,1464.85,4394.55,0.0,,3.0
5,1205910001004282,ABHAY PREMDAS TEMBHURNE [NGPM071],INE894V01022,BELRISE INDUSTRIE-EQ,3.0,219.15,657.45,0.0,,3.0

In [11]:
df_final["Client Name"] = (
    df_final["Client Name"]
    .str.strip()
    .str.replace(r"\s+", " ", regex=True)
)

In [12]:
df_final["Client Code"] = df_final["Client Name"].str.extract(r"\[([A-Z]{2,5}\d+)\]")

In [13]:
df_final["Client Name"] = (
    df_final["Client Name"]
    .str.replace(r"\s*\[[A-Z]{2,5}\d+\]", "", regex=True)
    .str.strip()
    .str.replace(r"\s+", " ", regex=True)
)

In [14]:
df3=pd.read_csv("/content/drive/My Drive/Pranamya Financial Services/DAILY DATA/Input folder/EQUITY_L.csv")
df3.head()

,SYMBOL,NAME OF COMPANY,SERIES,DATE OF LISTING,PAID UP VALUE,MARKET LOT,ISIN NUMBER,FACE VALUE
0,20MICRONS,20 Microns Limited,EQ,06-OCT-2008,5,1,INE144J01027,5
1,21STCENMGM,21st Century Management Services Limited,EQ,03-MAY-1995,10,1,INE253B01015,10
2,360ONE,360 ONE WAM LIMITED,EQ,19-SEP-2019,1,1,INE466L01038,1
3,3IINFOLTD,3i Infotech Limited,EQ,22-OCT-2021,10,1,INE748C01038,10
4,3MINDIA,3M India Limited,EQ,13-AUG-2004,10,1,INE470A01017,10

In [15]:
df3.columns = (
    df3.columns
        .str.strip()                # remove leading & trailing spaces
        .str.replace(r'\s+', ' ', regex=True)  # replace multiple spaces with single space
)

In [16]:
df3.columns

Index(['SYMBOL', 'NAME OF COMPANY', 'SERIES', 'DATE OF LISTING',
       'PAID UP VALUE', 'MARKET LOT', 'ISIN NUMBER', 'FACE VALUE'],
      dtype='object')

In [17]:
df_final = df_final.merge(
    df3[['ISIN NUMBER', 'SYMBOL']],
    left_on='ISIN Code',
    right_on='ISIN NUMBER',
    how='left'
)

# Optional: drop the extra ISIN NUMBER column after merge
df_final = df_final.drop(columns=['ISIN NUMBER'])

In [18]:


sheet_id = "1wwsN_YwPDUg1J1LMAseUqxd-KJyEhkOudS9aF8PIYwM"
sheet_name = "Sheet1"

url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}"

df_coupon = pd.read_csv(url)
df_coupon.head()

,ISIN Code,ISIN Description,SYMBOL,Face value,Amount 1,Date 1,Amount 2,Date 2,Amount 3,Date 3,Amount 4,Date 4,Dividend,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,INE00FF01025,ACUTAAS CHEM-EQ5/-,ACUTAAS,NaN,1.5,18 Sep 2025,NaN,NaN,NaN,NaN,NaN,NaN,1.5,NaN,NaN,NaN,NaN
1,INE931S01010,ADANI ENERGY-EQ,ADANIENSOL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
2,INE371P01015,AMBER ENTERPRISES-EQ,AMBER,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
3,INE438A01022,APOLLO TYRES-EQ RE 1,APOLLOTYRE,NaN,3.5,10-Feb,NaN,NaN,NaN,NaN,NaN,NaN,3.5,NaN,NaN,NaN,NaN
4,INE439A01020,ASAHI INDIA RE 1/-,ASAHIINDIA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN

In [19]:
df_final = df_final.merge(df_coupon[['ISIN Code', 'Dividend','Amount 1','Date 1','Amount 2','Date 2','Amount 3','Date 3']],
                         on='ISIN Code',
                         how='left')
df_final.head()

,Client Code,Client Name,ISIN Code,ISIN Description,Total Balance,Closing Rate,Holding Valuation,Pledged/ Freeze,Unnamed: 6,Free Balance,SYMBOL,Dividend,Amount 1,Date 1,Amount 2,Date 2,Amount 3,Date 3
0,NGPM071,ABHAY PREMDAS TEMBHURNE,INE00FF01025,ACUTAAS CHEM-EQ5/-,5.0,2372.80,11864.00,0.0,,5.0,ACUTAAS,1.50,1.5,18 Sep 2025,NaN,NaN,NaN,NaN
1,NGPM071,ABHAY PREMDAS TEMBHURNE,INE931S01010,ADANI ENERGY-EQ,2.0,1265.30,2530.60,0.0,,2.0,ADANIENSOL,0.00,NaN,NaN,NaN,NaN,NaN,NaN
2,NGPM071,ABHAY PREMDAS TEMBHURNE,INE006I01046,ASTRAL LIMITED-EQ,1.0,1583.75,1583.75,0.0,,1.0,ASTRAL,3.75,2.25,14 August 2025,1.50,11 November 2025,NaN,NaN
3,NGPM071,ABHAY PREMDAS TEMBHURNE,INE871C01038,AVANTI FEEDS-EQ1/-,3.0,1464.85,4394.55,0.0,,3.0,AVANTIFEED,9.00,9,7 Aug 2025,NaN,NaN,NaN,NaN
4,NGPM071,ABHAY PREMDAS TEMBHURNE,INE894V01022,BELRISE INDUSTRIE-EQ,3.0,219.15,657.45,0.0,,3.0,BELRISE,3.40,0.9,14 Aug 2025,0.55,22 Aug 2025,1.95,06 March 2026

In [20]:
df_final['Free Balance']=df_final['Free Balance'].astype(int)
df_final['ISIN Description']=df_final['ISIN Description']
df_final['Total Balance']=df_final['Total Balance'].astype(int)
df_final['Closing Rate']=df_final['Closing Rate'].astype(int)
df_final['Holding Valuation']=df_final['Holding Valuation'].astype(int)

df_final['Total Dividend']=df_final['Dividend']*df_final['Free Balance']
#df_final['Total Dividend']=df_final['Total Dividend'].astype(int)
df_final.head()

,Client Code,Client Name,ISIN Code,ISIN Description,Total Balance,Closing Rate,Holding Valuation,Pledged/ Freeze,Unnamed: 6,Free Balance,SYMBOL,Dividend,Amount 1,Date 1,Amount 2,Date 2,Amount 3,Date 3,Total Dividend
0,NGPM071,ABHAY PREMDAS TEMBHURNE,INE00FF01025,ACUTAAS CHEM-EQ5/-,5,2372,11864,0.0,,5,ACUTAAS,1.50,1.5,18 Sep 2025,NaN,NaN,NaN,NaN,7.50
1,NGPM071,ABHAY PREMDAS TEMBHURNE,INE931S01010,ADANI ENERGY-EQ,2,1265,2530,0.0,,2,ADANIENSOL,0.00,NaN,NaN,NaN,NaN,NaN,NaN,0.00
2,NGPM071,ABHAY PREMDAS TEMBHURNE,INE006I01046,ASTRAL LIMITED-EQ,1,1583,1583,0.0,,1,ASTRAL,3.75,2.25,14 August 2025,1.50,11 November 2025,NaN,NaN,3.75
3,NGPM071,ABHAY PREMDAS TEMBHURNE,INE871C01038,AVANTI FEEDS-EQ1/-,3,1464,4394,0.0,,3,AVANTIFEED,9.00,9,7 Aug 2025,NaN,NaN,NaN,NaN,27.00
4,NGPM071,ABHAY PREMDAS TEMBHURNE,INE894V01022,BELRISE INDUSTRIE-EQ,3,219,657,0.0,,3,BELRISE,3.40,0.9,14 Aug 2025,0.55,22 Aug 2025,1.95,06 March 2026,10.20

In [21]:
df4=pd.read_excel("/content/drive/My Drive/Pranamya Financial Services/DAILY DATA/Input folder/market capitalisation.xlsx",header=1)
df4.head()

,Sr. No.,Company name,ISIN,BSE Symbol,BSE 6 month Avg Total Market Cap in (Rs. Crs.),NSE Symbol,NSE 6 month Avg Total Market Cap (Rs. Crs.),MSEI Symbol,MSEI 6 month Avg Total Market Cap in (Rs Crs.),Average of All Exchanges (Rs. Cr.),"Categorization as per SEBI Circular dated Oct 6, 2017"
0,1,Reliance Industries Ltd,INE002A01018,RELIANCE,1970806.485079,RELIANCE,1970787.69,-,-,1.970797e+06,Large Cap
1,2,HDFC Bank Ltd.,INE040A01034,HDFCBANK,1516760.977763,HDFCBANK,1515580.9045,-,-,1.516171e+06,Large Cap
2,3,Bharti Airtel Ltd.,INE397D01024,BHARTIARTL,1195614.675865,BHARTIARTL,1195675.6905,-,-,1.195645e+06,Large Cap
3,4,Tata Consultancy Services Ltd.,INE467B01029,TCS,1129581.998484,TCS,1129555.15,-,-,1.129569e+06,Large Cap
4,5,ICICI Bank Ltd.,INE090A01021,ICICIBANK,999123.080253,ICICIBANK,998630.6377,-,-,9.988769e+05,Large Cap

In [22]:
import pandas as pd

# ------------------------------------------------------------
# Merge SEBI market cap data from df4 into df_final via ISIN
# ------------------------------------------------------------

# 1. Pick the column you want from df4 (last column = SEBI category label)
sebi_col = df4.columns[-1]
print("Column being merged from df4:", sebi_col)

# 2. Clean ISIN values on both sides
df_final['ISIN Code'] = df_final['ISIN Code'].astype(str).str.strip().str.upper()
df4['ISIN']           = df4['ISIN'].astype(str).str.strip().str.upper()

# 3. Keep only ISIN + required column from df4, remove duplicates
df4_slim = df4[['ISIN', sebi_col]].drop_duplicates(subset='ISIN')

# 4. Left-join onto df_final
df_final = df_final.merge(
    df4_slim,
    left_on='ISIN Code',
    right_on='ISIN',
    how='left'
)

# 5. Drop the redundant ISIN column from df4
df_final = df_final.drop(columns=['ISIN'])

# 6. Rename the merged column to 'Category'
df_final = df_final.rename(columns={sebi_col: 'Category'})

# ------------------------------------------------------------
# Match report
# ------------------------------------------------------------
matched   = df_final['Category'].notna().sum()
total     = len(df_final)
unmatched = df_final.loc[df_final['Category'].isna(), 'ISIN Code'].unique()

print(f"Matched  : {matched} / {total} rows")
print(f"Unmatched: {len(unmatched)} unique ISINs")
print("Sample unmatched ISINs:", unmatched[:10])

df_final.head()

Column being merged from df4: Categorization as per SEBI Circular dated Oct 6, 2017
Matched  : 1460 / 2246 rows
Unmatched: 61 unique ISINs
Sample unmatched ISINs: ['INE041025011' 'IN0020240142' 'IN0020220094' 'INF109KC19W1'
 'INE1JAR25012' 'INF769K01LY7' 'INE745G01043' 'INE721I01024'
 'INF204KC1402' 'INF732E01037']

,Client Code,Client Name,ISIN Code,ISIN Description,Total Balance,Closing Rate,Holding Valuation,Pledged/ Freeze,Unnamed: 6,Free Balance,SYMBOL,Dividend,Amount 1,Date 1,Amount 2,Date 2,Amount 3,Date 3,Total Dividend,Category
0,NGPM071,ABHAY PREMDAS TEMBHURNE,INE00FF01025,ACUTAAS CHEM-EQ5/-,5,2372,11864,0.0,,5,ACUTAAS,1.50,1.5,18 Sep 2025,NaN,NaN,NaN,NaN,7.50,Small Cap
1,NGPM071,ABHAY PREMDAS TEMBHURNE,INE931S01010,ADANI ENERGY-EQ,2,1265,2530,0.0,,2,ADANIENSOL,0.00,NaN,NaN,NaN,NaN,NaN,NaN,0.00,Large Cap
2,NGPM071,ABHAY PREMDAS TEMBHURNE,INE006I01046,ASTRAL LIMITED-EQ,1,1583,1583,0.0,,1,ASTRAL,3.75,2.25,14 August 2025,1.50,11 November 2025,NaN,NaN,3.75,Mid Cap
3,NGPM071,ABHAY PREMDAS TEMBHURNE,INE871C01038,AVANTI FEEDS-EQ1/-,3,1464,4394,0.0,,3,AVANTIFEED,9.00,9,7 Aug 2025,NaN,NaN,NaN,NaN,27.00,Small Cap
4,NGPM071,ABHAY PREMDAS TEMBHURNE,INE894V01022,BELRISE INDUSTRIE-EQ,3,219,657,0.0,,3,BELRISE,3.40,0.9,14 Aug 2025,0.55,22 Aug 2025,1.95,06 March 2026,10.20,Small Cap

In [23]:
import pandas as pd
import gspread
from gspread_dataframe import set_with_dataframe
from google.oauth2.service_account import Credentials

# ============================================================
# STEP 1: Asset classifier for unmatched ISINs (NaN bucket)
# ============================================================
def classify_asset(isin_desc):
    isin_desc = str(isin_desc).upper()
    if 'SGB' in isin_desc or 'GLD' in isin_desc or 'GOLD' in isin_desc:
        return 'Gold'
    elif 'REIT' in isin_desc or 'INVIT' in isin_desc:
        return 'REIT/InvIT'
    elif 'GS' in isin_desc or 'GSEC' in isin_desc or 'GOVT' in isin_desc:
        return 'Govt Securities'
    elif 'LIQ' in isin_desc or 'RTLIQBEES' in isin_desc or 'LIQUID' in isin_desc:
        return 'Liquid'
    elif 'SILVER' in isin_desc or 'SILVERBEES' in isin_desc:
        return 'Silver'
    else:
        return 'Other Equity'   # residual equity not in SEBI list

# ============================================================
# STEP 2: Build final Category column
#   - If SEBI category exists (Large/Mid/Small Cap) -> use it
#   - If NaN -> fall back to classify_asset(ISIN Description)
# ============================================================
df_final['Category'] = df_final['Category'].where(
    df_final['Category'].notna(),
    df_final['ISIN Description'].apply(classify_asset)
)

# Clean up — sometimes blank strings or 'nan' text sneak in
df_final['Category'] = df_final['Category'].replace(
    {'': 'Other Equity', 'nan': 'Other Equity', 'NaN': 'Other Equity'}
)

# ============================================================
# STEP 3: Ensure Holding Valuation is numeric
# ============================================================
df_final['Holding Valuation'] = pd.to_numeric(
    df_final['Holding Valuation'], errors='coerce'
).fillna(0)

# ============================================================
# STEP 4: Client-wise totals (denominator)
# ============================================================
client_total = (
    df_final.groupby(['Client Code', 'Client Name'], as_index=False)['Holding Valuation']
            .sum()
            .rename(columns={'Holding Valuation': 'Total Holding'})
)

# ============================================================
# STEP 5: Client × Category aggregation + % allocation
# ============================================================
cat_value = (
    df_final.groupby(['Client Code', 'Client Name', 'Category'], as_index=False)['Holding Valuation']
            .sum()
)

cat_value = cat_value.merge(client_total, on=['Client Code', 'Client Name'])
cat_value['Allocation %'] = (
    cat_value['Holding Valuation'] / cat_value['Total Holding'] * 100
).round(2)

# ============================================================
# STEP 6: Pivot — wide format (one row per client)
# ============================================================
final_allocation = cat_value.pivot_table(
    index=['Client Code', 'Client Name'],
    columns='Category',
    values='Allocation %',
    fill_value=0
).reset_index()

# Preferred column order (only keeps those present)
preferred_order = [
    'Large Cap', 'Mid Cap', 'Small Cap',
    'REIT/InvIT', 'Govt Securities', 'Gold', 'Silver',
    'Liquid', 'Other Equity'
]
existing = [c for c in preferred_order if c in final_allocation.columns]
final_allocation = final_allocation[['Client Code', 'Client Name'] + existing]

# Attach Total Holding value + sanity check
final_allocation = final_allocation.merge(client_total, on=['Client Code', 'Client Name'])
final_allocation['Check Sum %'] = final_allocation[existing].sum(axis=1).round(2)

print(final_allocation.head(10))
print(f"\nTotal clients: {len(final_allocation)}")

# ============================================================
# STEP 7 (REVISED): Push to Google Sheets — prevent date coercion
# ============================================================
import gspread
from gspread_dataframe import set_with_dataframe
from gspread.utils import rowcol_to_a1
from google.oauth2.service_account import Credentials

SCOPES = [
    "https://www.googleapis.com/auth/spreadsheets",
    "https://www.googleapis.com/auth/drive"
]

creds = Credentials.from_service_account_file(
    "/content/drive/My Drive/Pranamya Financial Services/gsheets-automation-486706-263c21d2a607.json",
    scopes=SCOPES
)

client = gspread.authorize(creds)
spreadsheet = client.open_by_key("1M9Hehl1Uyr-sUbCgw4qxMalRqZPMtDRql1Kv03fLSbk")

tab_name = "Asset Allocation %"
try:
    worksheet = spreadsheet.worksheet(tab_name)
    worksheet.clear()
except gspread.WorksheetNotFound:
    worksheet = spreadsheet.add_worksheet(
        title=tab_name,
        rows=len(final_allocation) + 5,
        cols=len(final_allocation.columns) + 2
    )

# ---- FIX 1: Force all numeric columns to float (not object) ----
numeric_cols = [c for c in final_allocation.columns
                if c not in ['Client Code', 'Client Name']]
for c in numeric_cols:
    final_allocation[c] = pd.to_numeric(final_allocation[c], errors='coerce').fillna(0).astype(float)

# Write data
set_with_dataframe(worksheet, final_allocation)

# ---- FIX 2: Force number format on numeric columns AFTER writing ----
# This prevents Sheets from auto-detecting as date
n_rows = len(final_allocation) + 1   # +1 for header
n_cols = len(final_allocation.columns)

# Get column letter range for numeric columns (cols 3 onwards = C onwards)
start_cell = rowcol_to_a1(2, 3)                    # e.g. C2
end_cell   = rowcol_to_a1(n_rows, n_cols)          # e.g. L250

worksheet.format(f"{start_cell}:{end_cell}", {
    "numberFormat": {
        "type": "NUMBER",
        "pattern": "0.00"
    }
})

print(f"✅ Google Sheet updated → tab: '{tab_name}' with number formatting applied")

  Client Code                Client Name  Large Cap  Mid Cap  Small Cap  \
0     BDM0431         SANDIP KISAN DANGE      16.28     7.31      17.16
1     NGPM002       ANITA BHIMAPPA DESAI       0.00     0.00       0.00
2     NGPM003   SANJOG VASANTRAO JICHKAR      22.62     4.47      12.22
3     NGPM004      PALLAVI SUDHIR BODKHE      23.00     5.79      15.63
4     NGPM006  NETAJI CHANDRAKANT FEGADE       8.73     5.85       8.41
5     NGPM007   VIJAYA ANIRUDDHA PURANIK       7.51     3.92       6.30
6     NGPM008             SAURABH SHARMA      10.62     6.09      14.38
7     NGPM009             SHREYA JAISWAL      15.34     7.84      10.70
8     NGPM010     VAIBHAV GANGADHAR MERU       5.57     5.63       3.10
9     NGPM011   POOJA RAVIKUMAR GHOSEKAR       9.65     7.00      11.37

   REIT/InvIT  Govt Securities    Gold  Silver  Liquid  Other Equity  \
0        2.10            43.81    5.46    5.56    0.00          2.33
1        0.00             0.00  100.00    0.00    0.00          0.00
2        3.37             4.01   45.44    7.68    0.00          0.18
3        3.49             6.51   31.68   10.22    0.00          3.68
4        1.73             9.85   59.82    2.89    0.00          2.72
5        1.04            42.65   31.47    4.77    1.45          0.90
6        1.62             1.70   47.48   11.59    0.00          6.52
7        1.79             3.67   54.05    2.13    0.01          4.47
8        9.24            12.78   60.44    0.00    0.00          3.24
9        2.82             4.58   49.18   11.45    0.00          3.95

   Total Holding  Check Sum %
0         245509       100.01
1         215647       100.00
2        8875076        99.99
3         589597       100.00
4        1848876       100.00
5         692771       100.01
6         603666       100.00
7        7363248       100.00
8         201198       100.00
9        1127328       100.00

Total clients: 60
✅ Google Sheet updated → tab: 'Asset Allocation %' with number formatting applied

In [24]:
# Select only required columns
df_required = df_final[['Client Name', 'ISIN Description', 'Total Balance']]

# Create pivot table
pivot_df = pd.pivot_table(
    df_required,
    index='Client Name',            # rows
    columns='ISIN Description',      # columns
    values='Total Balance',          # cell values
    aggfunc='sum',                   # sum in case of duplicates
    fill_value=0                     # replace NaN with 0
)

# Optional: reset index if you want Client Name as a column
pivot_df = pivot_df.reset_index()

In [25]:
# Open existing Google Sheet
spreadsheet = client.open_by_key("1M9Hehl1Uyr-sUbCgw4qxMalRqZPMtDRql1Kv03fLSbk")
#worksheet = spreadsheet.sheet1


# Select Sheet2
worksheet = spreadsheet.worksheet("Share Wise_details")


# Clear old data (optional but recommended)
worksheet.clear()

# Write dataframe
set_with_dataframe(worksheet, pivot_df)

print("Google Sheet updated successfully")

Google Sheet updated successfully

In [26]:
# Group and sum Total Dividend for each Client Name
df_dividend_summary = df_final.groupby('Client Name', as_index=False)['Total Dividend'].sum()

# Rename column for clarity (optional)
df_dividend_summary.rename(columns={'Total Dividend': 'Total Dividend Sum'}, inplace=True)

# Display result
df_dividend_summary.head()

                   Client Name  Total Dividend Sum
0      ABHAY PREMDAS TEMBHURNE             5422.34
1      ABHAY SHARAD GHODKHANDE              484.14
2    AFTAB ALIMOHAMMAD DHANANI             4092.87
3             AJIT DINKAR MORE            53007.88
4  AKSHATA BHALCHANDRA MANKARI             8862.13

In [27]:
df_dividend_summary['Client Name'] = (
    df_dividend_summary['Client Name']
    .str.replace(r'\s*\[.*?\]', '', regex=True)
    .str.strip()
)
df_dividend_summary.head()

                   Client Name  Total Dividend Sum
0      ABHAY PREMDAS TEMBHURNE             5422.34
1      ABHAY SHARAD GHODKHANDE              484.14
2    AFTAB ALIMOHAMMAD DHANANI             4092.87
3             AJIT DINKAR MORE            53007.88
4  AKSHATA BHALCHANDRA MANKARI             8862.13

In [28]:
# 6. Save cleaned output
output_path = '/content/drive/My Drive/Pranamya Financial Services/DAILY DATA/Output folder/Holdings123.xlsx'
df_final.to_excel(output_path, index=False)

print("File saved successfully at:", output_path)

File saved successfully at: /content/drive/My Drive/Pranamya Financial Services/DAILY DATA/Output folder/Holdings123.xlsx

In [29]:
# Open existing Google Sheet
spreadsheet = client.open_by_key("1M9Hehl1Uyr-sUbCgw4qxMalRqZPMtDRql1Kv03fLSbk")
#worksheet = spreadsheet.sheet1

# Select Sheet3
worksheet = spreadsheet.worksheet("dividend_summary")


# Clear old data (optional but recommended)
worksheet.clear()



# Write dataframe
set_with_dataframe(worksheet, df_dividend_summary)

print("Google Sheet updated successfully")

Google Sheet updated successfully

In [30]:
df_final["Client Code"] = df_final["Client Name"].str.extract(r"\[([A-Z]{2,5}\d+)\]")

In [31]:
df_final["Client Name"] = df_final["Client Name"].str.replace(
    r"\s*\[[A-Z]{2,5}\d+\]",
    "",
    regex=True
)

In [32]:
df_sharePrice=df_final[['ISIN Code','ISIN Description','Closing Rate']]

df_sharePrice['Date'] = pd.Timestamp.today().date()

df_sharePrice.head(10)

/tmp/ipykernel_1024/3778329044.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sharePrice['Date'] = pd.Timestamp.today().date()

      ISIN Code      ISIN Description  Closing Rate        Date
0  INE00FF01025    ACUTAAS CHEM-EQ5/-          2372  2026-04-23
1  INE931S01010       ADANI ENERGY-EQ          1265  2026-04-23
2  INE006I01046     ASTRAL LIMITED-EQ          1583  2026-04-23
3  INE871C01038    AVANTI FEEDS-EQ1/-          1464  2026-04-23
4  INE894V01022  BELRISE INDUSTRIE-EQ           219  2026-04-23
5  INE263A01024  BHARAT ELECTRONIC-EQ           451  2026-04-23
6  INE465A01025  BHARAT FORGE-NEW RS2          1895  2026-04-23
7  INE118H01025    BSE LIMITED-EQ 2/-          3515  2026-04-23
8  INE495A01022  DALMIA BHARA EQ RS 2           383  2026-04-23
9  INE0I3401014        DHAMPUR BIO-EQ           113  2026-04-23

In [33]:
 #6. Save cleaned output
output_path = "/content/drive/My Drive/Pranamya Financial Services/DAILY DATA/Output folder/Share Price.xlsx"
df_sharePrice.to_excel(output_path, index=False)

print("File saved successfully at:", output_path)

File saved successfully at: /content/drive/My Drive/Pranamya Financial Services/DAILY DATA/Output folder/Share Price.xlsx

In [34]:
# Open existing Google Sheet
spreadsheet = client.open_by_key("1M9Hehl1Uyr-sUbCgw4qxMalRqZPMtDRql1Kv03fLSbk")
#worksheet = spreadsheet.sheet1

# Select Sheet4
worksheet = spreadsheet.worksheet("Share Price")

# Clear old data (optional but recommended)
worksheet.clear()

# Write dataframe
set_with_dataframe(worksheet, df_sharePrice)

print("Google Sheet updated successfully")

Google Sheet updated successfully

In [35]:
# Group and sum Total Dividend for each Client Name
df_Holding_summary = df_final.groupby('Client Name', as_index=False)['Holding Valuation'].sum()



# Display result
df_Holding_summary.head()

                   Client Name  Holding Valuation
0      ABHAY PREMDAS TEMBHURNE             298519
1      ABHAY SHARAD GHODKHANDE             303203
2    AFTAB ALIMOHAMMAD DHANANI             863382
3             AJIT DINKAR MORE            1781880
4  AKSHATA BHALCHANDRA MANKARI            1093298

In [36]:
# Open existing Google Sheet
spreadsheet = client.open_by_key("1M9Hehl1Uyr-sUbCgw4qxMalRqZPMtDRql1Kv03fLSbk")
#worksheet = spreadsheet.sheet1

# Select Sheet5
worksheet = spreadsheet.worksheet("holding_details")

# Clear old data (optional but recommended)
worksheet.clear()

# Write dataframe
set_with_dataframe(worksheet, df_Holding_summary)

print("Google Sheet updated successfully")

Google Sheet updated successfully

In [37]:
df_Holding_summary.sum()

Client Name          ABHAY PREMDAS TEMBHURNEABHAY SHARAD GHODKHANDE...
Holding Valuation                                             50778535
dtype: object

In [38]:
df_final.head()

,Client Code,Client Name,ISIN Code,ISIN Description,Total Balance,Closing Rate,Holding Valuation,Pledged/ Freeze,Unnamed: 6,Free Balance,SYMBOL,Dividend,Amount 1,Date 1,Amount 2,Date 2,Amount 3,Date 3,Total Dividend,Category
0,NaN,ABHAY PREMDAS TEMBHURNE,INE00FF01025,ACUTAAS CHEM-EQ5/-,5,2372,11864,0.0,,5,ACUTAAS,1.50,1.5,18 Sep 2025,NaN,NaN,NaN,NaN,7.50,Small Cap
1,NaN,ABHAY PREMDAS TEMBHURNE,INE931S01010,ADANI ENERGY-EQ,2,1265,2530,0.0,,2,ADANIENSOL,0.00,NaN,NaN,NaN,NaN,NaN,NaN,0.00,Large Cap
2,NaN,ABHAY PREMDAS TEMBHURNE,INE006I01046,ASTRAL LIMITED-EQ,1,1583,1583,0.0,,1,ASTRAL,3.75,2.25,14 August 2025,1.50,11 November 2025,NaN,NaN,3.75,Mid Cap
3,NaN,ABHAY PREMDAS TEMBHURNE,INE871C01038,AVANTI FEEDS-EQ1/-,3,1464,4394,0.0,,3,AVANTIFEED,9.00,9,7 Aug 2025,NaN,NaN,NaN,NaN,27.00,Small Cap
4,NaN,ABHAY PREMDAS TEMBHURNE,INE894V01022,BELRISE INDUSTRIE-EQ,3,219,657,0.0,,3,BELRISE,3.40,0.9,14 Aug 2025,0.55,22 Aug 2025,1.95,06 March 2026,10.20,Small Cap

In [39]:
import os
import re

BASE_DIR = "/content/drive/My Drive/Pranamya Financial Services/Clients"   # change if needed

In [40]:
def clean_name(name):
    return re.sub(r'[\\/*?:"<>|]', '', name).strip()

In [41]:
import numpy as np

# ── Load Ledger files (for Cash Details sheet) ──────────────────────────
ledger_base = "/content/drive/My Drive/Pranamya Financial Services/DAILY DATA/Yearly Ledger"

df_led1 = pd.read_excel(f"{ledger_base}/2023-24/LEDGER_01-01-24_to_31-03-24__7DI0XNNOZ.XLSX", header=1)
df_led2 = pd.read_excel(f"{ledger_base}/2024-25/LEDGER_01-04-24_to_31-03-25__7DI0URBHR.XLSX", header=1)
df_led3 = pd.read_excel(f"{ledger_base}/2025-26/LEDGER_01-04-25_to_31-03-26_.XLSX", header=1)
df_led4 = pd.read_excel(f"{ledger_base}/2026-2027/LEDGER_01-04-26_to_31-03-27__7FX0LGNCB.XLSX", header=1)


# ── Standardize column names for each file before concat ────────────────
def standardize_ledger_columns(df):
    """Rename columns to a common format regardless of source file format."""
    rename_map = {}
    for col in df.columns:
        col_clean = col.replace("_x000D_", "").replace("\n", " ").replace("\r", " ").strip()
        col_lower = col_clean.lower()
        if "voucher" in col_lower and "date" in col_lower:
            rename_map[col] = "Date"
        elif "entry" in col_lower and "detail" in col_lower:
            rename_map[col] = "Details"
        elif "amount" in col_lower and "debit" in col_lower:
            rename_map[col] = "Debit"
        elif "amount" in col_lower and "credit" in col_lower:
            rename_map[col] = "Credit"
        elif "running" in col_lower and "balance" in col_lower:
            rename_map[col] = "Balance"
    df = df.rename(columns=rename_map)
    # Drop unwanted columns
    drop_cols = [c for c in df.columns if c in ['Branch', 'Sett#', 'DrCr'] or c.startswith('Unnamed')]
    df = df.drop(columns=drop_cols, errors='ignore')
    return df

df_led1 = standardize_ledger_columns(df_led1)
df_led2 = standardize_ledger_columns(df_led2)
df_led3 = standardize_ledger_columns(df_led3)
df_led4 = standardize_ledger_columns(df_led4)

df_ledger = pd.concat([df_led1, df_led2, df_led3, df_led4], axis=0, ignore_index=True)

# Extract and forward-fill client names
df_ledger["Client_Name"] = np.where(
    df_ledger["Date"].astype(str).str.contains(r"\[.*\]", na=False),
    df_ledger["Date"],
    np.nan
)
df_ledger["Client_Name"] = df_ledger["Client_Name"].ffill()

# Filter only BANK CLIENT A/C rows
df_cash = df_ledger[
    df_ledger["Details"].str.contains(
        r"\bBANK\b.*\bCLIENT\b.*\b(A\s*/\s*C|AC|ACCOUNT)\b",
        case=False, na=False, regex=True
    )
].copy()

# Extract Client Code and clean Client Name — strip + normalize spaces
df_cash["Client Code"] = df_cash["Client_Name"].str.extract(r"\[([A-Z]{2,5}\d+)\]")
df_cash["Client Name"] = (
    df_cash["Client_Name"]
    .str.replace(r"\s*\[[A-Z]{2,5}\d+\]", "", regex=True)
    .str.strip()
    .str.replace(r"\s+", " ", regex=True)
)
df_cash = df_cash.drop(columns=["Client_Name"])

print(f"Cash details loaded: {len(df_cash)} rows for {df_cash['Client Name'].nunique()} clients")

Cash details loaded: 1079 rows for 62 clients

/tmp/ipykernel_1024/3058775061.py:52: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df_ledger["Details"].str.contains(

In [42]:
import pandas as pd
import re
from datetime import datetime
import gspread
from gspread_dataframe import set_with_dataframe

# ======================================================================
# STEP 1: Ensure columns are correctly named
# ======================================================================
# If df_led4 was read with header=None, set column names explicitly
# Expected structure: Date | Branch | Sett# | Details | Debit | Credit | Balance | DrCr | Extra
if df_led4.columns[0] != 'Date':
    df_led4.columns = ['Date', 'Branch', 'Sett', 'Details', 'Debit', 'Credit', 'Balance', 'DrCr', 'Extra'][:len(df_led4.columns)]

# ======================================================================
# STEP 2: Identify client header rows (e.g. "ABHAY PREMDAS TEMBHURNE [NGPM071]")
# Client name appears in the 'Date' column in header rows
# ======================================================================
client_pattern = re.compile(r'^([A-Z][A-Z\s\.]+?\s*\[[A-Z0-9]+\])\s*$')

def extract_client(val):
    if pd.isna(val) or not isinstance(val, str):
        return None
    m = client_pattern.match(val.strip())
    return m.group(1).strip() if m else None

df_led4['_client_tag'] = df_led4['Date'].apply(extract_client)
df_led4['_client'] = df_led4['_client_tag'].ffill()   # propagate client name downward

# ======================================================================
# STEP 3: Clean numeric + date columns
# ======================================================================
df_led4['_date']   = pd.to_datetime(df_led4['Date'], format='%d/%m/%Y', errors='coerce')
df_led4['_debit']  = pd.to_numeric(df_led4['Debit'], errors='coerce').fillna(0)
df_led4['_credit'] = pd.to_numeric(df_led4['Credit'], errors='coerce').fillna(0)

# ======================================================================
# STEP 4: Filter last 1 month & identify PAYOUTS (money sent back to client's bank)
# Rule: dated row + Details contains "HDFC BANK" + amount in Debit column
# (Pay-ins like "HDFC BANK CLIENT ACCOUNT [F&O]" have amount in Credit, so auto-excluded)
# ======================================================================
today = pd.Timestamp(datetime.today().date())
one_month_ago = today - pd.DateOffset(months=1)

payout_mask = (
    df_led4['_date'].notna()
    & (df_led4['_debit'] > 0)
    & df_led4['Details'].astype(str).str.contains('HDFC BANK', case=False, na=False)
    & (df_led4['_date'] >= one_month_ago)
    & (df_led4['_date'] <= today)
)

payouts = df_led4[payout_mask].copy()

print(f"Period: {one_month_ago.strftime('%d/%m/%Y')} to {today.strftime('%d/%m/%Y')}")
print(f"Total payout transactions found: {len(payouts)}")
print(f"Grand total debit to bank: ₹{payouts['_debit'].sum():,.2f}\n")

# ======================================================================
# STEP 5: Build per-client summary
# ======================================================================
summary_df = (
    payouts.groupby('_client')
           .agg(**{
               'Total Debit to Bank': ('_debit', 'sum'),
               'No. of Transactions': ('_debit', 'count'),
               'Last Payout Date': ('_date', 'max')
           })
           .reset_index()
           .rename(columns={'_client': 'Client Name'})
)

summary_df['Last Payout Date'] = summary_df['Last Payout Date'].dt.strftime('%d/%m/%Y')
summary_df['Period From']  = one_month_ago.strftime('%d/%m/%Y')
summary_df['Period To']    = today.strftime('%d/%m/%Y')
summary_df['Last Updated'] = datetime.now().strftime('%d/%m/%Y %H:%M')

summary_df = summary_df[['Client Name', 'Period From', 'Period To',
                         'Total Debit to Bank', 'No. of Transactions',
                         'Last Payout Date', 'Last Updated']]

print(summary_df.to_string(index=False))

# ======================================================================
# STEP 6: Write to Google Sheet → "debit balance" worksheet
# ======================================================================
spreadsheet = client.open_by_key("1M9Hehl1Uyr-sUbCgw4qxMalRqZPMtDRql1Kv03fLSbk")

try:
    master_ws = spreadsheet.worksheet("debit balance")
    master_ws.clear()
except gspread.exceptions.WorksheetNotFound:
    master_ws = spreadsheet.add_worksheet(title="debit balance", rows=1000, cols=10)

set_with_dataframe(master_ws, summary_df)

# Clean up helper columns
df_led4.drop(columns=['_client_tag', '_client', '_date', '_debit', '_credit'],
             inplace=True, errors='ignore')

print(f"\n✅ {len(summary_df)} clients written to 'debit balance' sheet")

Period: 23/03/2026 to 23/04/2026
Total payout transactions found: 12
Grand total debit to bank: ₹45,264.78

                         Client Name Period From  Period To  Total Debit to Bank  No. of Transactions Last Payout Date     Last Updated
    AMRUT GURUDATTA SHINDE [NGPM047]  23/03/2026 23/04/2026             25240.00                    1       06/04/2026 23/04/2026 04:28
  BADALKUMAR YUVRAJ AKHADE [NGPM035]  23/03/2026 23/04/2026                 0.10                    1       17/04/2026 23/04/2026 04:28
  DHANASHREE SAGAR BAGDIYA [NGPM068]  23/03/2026 23/04/2026                 3.47                    1       17/04/2026 23/04/2026 04:28
     KIRAN TEJKUMAR BEHARE [NGPM072]  23/03/2026 23/04/2026                 1.30                    1       17/04/2026 23/04/2026 04:28
  LOKESH MANOHARRAO BORADE [NGPM051]  23/03/2026 23/04/2026                 4.30                    1       17/04/2026 23/04/2026 04:28
MANISH PAWANKUMAR TIBDIWAL [NGPM020]  23/03/2026 23/04/2026                 1.00                    1       17/04/2026 23/04/2026 04:28
     RAJASHRI VAIBHAV MERU [NGPM073]  23/03/2026 23/04/2026                 5.77                    1       17/04/2026 23/04/2026 04:28
             RENUKA  PATIL [NGPM021]  23/03/2026 23/04/2026                 3.70                    1       17/04/2026 23/04/2026 04:28
    SAGAR SANGRAM BASANALE [NGPM057]  23/03/2026 23/04/2026                 5.97                    1       17/04/2026 23/04/2026 04:28
           SAURABH  SHARMA [NGPM008]  23/03/2026 23/04/2026             19990.37                    1       17/04/2026 23/04/2026 04:28
       SNEHA NAGNATH SOLSE [NGPM049]  23/03/2026 23/04/2026                 3.60                    1       17/04/2026 23/04/2026 04:28
             SOUMYA MOKASI [NGPM028]  23/03/2026 23/04/2026                 5.20                    1       17/04/2026 23/04/2026 04:28

✅ 12 clients written to 'debit balance' sheet

In [43]:
for client_name, client_df in df_final.groupby("Client Name"):

    folder_name = clean_name(client_name).strip()
    folder_name = re.sub(r"\s+", " ", folder_name)  # normalize multi-spaces
    client_path = os.path.join(BASE_DIR, folder_name)

    if os.path.isdir(client_path):
        file_path = os.path.join(client_path, f"{folder_name}_HOLDINGS.xlsx")

        # Get this client's cash details
        client_cash = df_cash[df_cash["Client Name"] == client_name].copy()

        with pd.ExcelWriter(file_path, engine="openpyxl") as writer:
            client_df.to_excel(writer, sheet_name="Holdings", index=False)
            if not client_cash.empty:
                client_cash.to_excel(writer, sheet_name="Cash Details", index=False)

    else:
        print(f"Folder not found for client: {client_name}")

In [44]:
df['Date'] = pd.Timestamp.today().date()
df.head()

,ISIN Code,ISIN Description,Total Balance,Closing Rate,Holding Valuation,Pledged/ Freeze,Unnamed: 6,Free Balance,Client Code,Client Name,Date
0,1205910001004282 ABHAY PREMDAS TEMBHURNE [NGPM...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,2026-04-23
1,INE00FF01025,ACUTAAS CHEM-EQ5/-,5.0,2372.80,11864.00,0.0,,5.0,1205910001004282,ABHAY PREMDAS TEMBHURNE [NGPM071],2026-04-23
2,INE931S01010,ADANI ENERGY-EQ,2.0,1265.30,2530.60,0.0,,2.0,1205910001004282,ABHAY PREMDAS TEMBHURNE [NGPM071],2026-04-23
3,INE006I01046,ASTRAL LIMITED-EQ,1.0,1583.75,1583.75,0.0,,1.0,1205910001004282,ABHAY PREMDAS TEMBHURNE [NGPM071],2026-04-23
4,INE871C01038,AVANTI FEEDS-EQ1/-,3.0,1464.85,4394.55,0.0,,3.0,1205910001004282,ABHAY PREMDAS TEMBHURNE [NGPM071],2026-04-23